logisteps/urls.py
from django.urls import path
from . import views

app_name = 'logisteps'
urlpatterns = [
    path('', views.RecentView.as_view(), name='recent'),
    path('register/', views.register, name='register'),
    path('profile/complete/', views.completeProfile, name='complete_profile'),
    path('profile/update/', views.updateProfile, name='update_profile'),
    path('recent', views.RecentView.as_view(), name='recent'),
    path('steps_over_time', views.StepsOverTime.as_view(), name='steps_over_time'),
    path('steps_by_day', views.StepsByDay.as_view(), name='steps_by_day'),
    path('activity', views.Activity.as_view(), name='activity'),
    path('pressure', views.PressureView.as_view(), name='pressure'),
    path('map', views.MapView.as_view(), name='map')
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from logisteps import views

# router = routers.DefaultRouter()
# router.register(r'users', views.UserViewSet)
# router.register(r'groups', views.GroupViewSet)

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('logisteps/', include('logisteps.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('logisteps_api.urls')),
    path('', views.RecentView.as_view())
]

logisteps/models/location.py
from django.db import models

class Location(models.Model):
    latitude = models.FloatField()
    longitude = models.FloatField()

    def save(self, *args, **kwargs):
        super(Location, self).save(*args, **kwargs)

    def __str__(self):
        return 'ID: {}, Latitude: {}, Longitude: {}'.format(self.id, self.latitude, self.longitude)

logisteps/models/logistepsUser.py
from django.db import models
from django.contrib.auth.models import User
from .shoe import Shoe

from math import floor

# Create your models here.   

class LogistepsUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    height = models.IntegerField()
    weight = models.IntegerField()
    step_goal = models.IntegerField()
    left_shoe = models.OneToOneField(
        Shoe,
        related_name='user_left_shoe',
        on_delete=models.CASCADE
    )
    right_shoe = models.OneToOneField(
        Shoe,
        related_name='user_right_shoe',
        on_delete=models.CASCADE
    )

    class Meta:
        verbose_name = "LogiSteps User"
        verbose_name_plural = "LogiSteps Users"

    def __str__(self):
        return self.user.username
    
    @property
    def user__username(self):
        return self.user.username

    @property
    def fullname(self):
        return self.user.first_name + " " + self.user.last_name

    @property
    def height_ft(self):
        return floor(self.height / 12)

    @property
    def height_in(self):
        return self.height % 12
    
    def delete(self, *args, **kwargs):
        self.user.delete()
        self.left_shoe.delete()
        self.right_shoe.delete()
        return super().delete(*args, **kwargs)

logisteps/models/sensorReading.py
from django.db import models
from .shoe import Shoe
from .step import Step

class SensorReading(models.Model):
    LOCATION_CHOICES = (
        ('T', 'top'),
        ('B', 'bottom')
    )

    pressure = models.FloatField()
    location = models.CharField(max_length=1, choices=LOCATION_CHOICES)
    shoe = models.ForeignKey(Shoe, on_delete=models.CASCADE)
    step = models.ForeignKey(Step, related_name='sensor_readings', on_delete=models.CASCADE)

    def __str__(self):
        return 'Sensor: {}, Pressure reading: {}, Location: {}'.format(self.id, self.pressure, self.location)

logisteps/models/shoe.py
from django.db import models

class Shoe(models.Model):
    FOOT_CHOICES = (
        ('R', 'right'),
        ('L', 'left'),
    )
    size = models.DecimalField(max_digits=3, decimal_places=1)
    foot = models.CharField(max_length=1, choices=FOOT_CHOICES)

    class Meta:
        verbose_name = "Logisteps Smart Shoe"
        verbose_name_plural = "Logisteps Smart Shoes"

    def __str__(self):
        return 'ID: {}, size: {}, foot: {}'.format(self.id, self.size, self.foot)

logisteps/models/step.py
from django.db import models
# from .sensorReading import SensorReading
from .location import Location
from .logistepsUser import LogistepsUser

class Step(models.Model):
    datetime = models.DateTimeField(auto_now=False, auto_now_add=False)
    # left_sensor_reading = models.OneToOneField(SensorReading, on_delete=models.CASCADE)
    # right_sensor_reading = models.OneToOneField(SensorReading, on_delete=models.CASCADE)
    location = models.OneToOneField(Location, on_delete=models.CASCADE)
    user = models.ForeignKey(LogistepsUser, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Logisteps Step"
        verbose_name_plural = "Logisteps Steps"

    def __str__(self):
        return self.name
    
    def delete(self, *args, **kwargs):
        # self.left_sensor_reading.delete()
        # self.right_sensor_reading.delete()
        self.location.delete()
        return super().delete(*args, **kwargs)

logisteps/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from django import forms
from django.core.exceptions import ValidationError

from .models import Shoe, LogistepsUser

class CustomUserCreationForm(forms.Form):
    username = forms.CharField(label='Username', min_length=4, max_length=150)
    email = forms.EmailField(label='Email')
    first_name = forms.CharField(label="Firstname", max_length=50)
    last_name = forms.CharField(label="Lastname", max_length=50)
    password1 = forms.CharField(label='Enter password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = User.objects.filter(username=username)
        if r.count():
            raise ValidationError("Username already exists")
        return username

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        if r.count():
            raise ValidationError("Email already exists")
        return email
    
    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwords don't match")
        
        return password2
    
    def save(self, commit=True):
        user = User.objects.create_user(
            username=self.cleaned_data['username'],
            email=self.cleaned_data['email'],
            first_name=self.cleaned_data['first_name'],
            last_name=self.cleaned_data['last_name'],
            password=self.cleaned_data['password1']
        )

        return user

class UserCompletionForm(forms.Form):
    left_shoe = forms.DecimalField(label='Left Shoe Size', min_value=4, max_value=16, max_digits=3, decimal_places=1)
    right_shoe = forms.DecimalField(label='Right Shoe Size', min_value=4, max_value=16, max_digits=3, decimal_places=1)
    height_feet = forms.IntegerField(label='Height (ft.)', min_value=0, required=True)
    height_inches = forms.IntegerField(label='Height (in.)', min_value=0, max_value=12, required=True)
    weight = forms.IntegerField(min_value=0, required=True)
    step_goal = forms.IntegerField(label='Step Goal', min_value=0, required=True)

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(UserCompletionForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        lShoe = Shoe.objects.create(foot='L', size=self.cleaned_data['left_shoe'])
        rShoe = Shoe.objects.create(foot='R', size=self.cleaned_data['right_shoe'])

        height = self.cleaned_data['height_feet'] * 12 + self.cleaned_data['height_inches']

        logistepsUser = LogistepsUser.objects.create(left_shoe=lShoe, right_shoe=rShoe, height=height,
             weight=self.cleaned_data['weight'], step_goal=self.cleaned_data['step_goal'], user=self.user)

        lShoe.save()
        rShoe.save()
        logistepsUser.save()

        return logistepsUser

class ShoeUpdateForm(forms.ModelForm):
    class Meta:
        model = Shoe
        exclude = ('id', 'foot')

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name')

class LogistepsUserUpdateForm(forms.ModelForm):
    height_feet = forms.IntegerField(label='Height (ft.)', min_value=0, required=True)
    height_inches = forms.IntegerField(label='Height (in.)', min_value=0, max_value=12, required=True)

    class Meta:
        model = LogistepsUser
        exclude = ('user', 'left_shoe', 'right_shoe', 'height')
    
    def save(self, commit=True):
        self.instance.weight = self.cleaned_data['weight']
        self.instance.height = (self.cleaned_data['height_feet'] * 12) + self.cleaned_data['height_inches']
        self.instance.step_goal = self.cleaned_data['step_goal']
        
        self.instance.save()
        return self.instance

logisteps/views.py
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth import views as auth_views
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView
from django.views.generic import View
from datetime import datetime, timedelta
from django.views.generic.edit import UpdateView

from math import floor

from .models import LogistepsUser, Step, Shoe
from .forms import CustomUserCreationForm, UserCompletionForm, LogistepsUserUpdateForm, UserUpdateForm, ShoeUpdateForm
from utils.step_utils import getInactiveTime, getLeastActiveHour, getMostActiveHour, avgStepsPerHour, getDateSummary
from utils.helper import to12HourTime

# Create your views here.
def register(request):
    if request.method == 'POST':
        f = CustomUserCreationForm(request.POST)
        if f.is_valid():
            user = f.save()

            login(request, user)
            return redirect('/logisteps/profile/complete/')

    else:
        f = CustomUserCreationForm()

    return render(request, 'logisteps/register.html', {'form': f})

@method_decorator(login_required, name='dispatch')
class ProtectedView(TemplateView):
    template_name = 'secret.html'

class IndexView(ProtectedView):
    template_name = 'index.html'

    # def dispatch(self, request, *args, **kwargs):
    #     # parse the request here ie.
    #     self.logistepsUser = request.GET.get('user', None)
    #     print(self.logistepsUser)

    #     # call the view
    #     return super(IndexView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return render(request, 'logisteps/index.html')

@login_required
def completeProfile(request):
    if request.method == 'POST':
        f = UserCompletionForm(request.user, request.POST)
        if f.is_valid():
            f.save()

            return redirect('/logisteps/')

    else:
        f = UserCompletionForm(request.user)

    return render(request, 'logisteps/complete_profile.html', {'form': f})

@login_required
def updateProfile(request):
    logistepsUser = get_object_or_404(LogistepsUser, user_id=request.user.id)
    left_shoe = get_object_or_404(Shoe, id=logistepsUser.left_shoe_id)
    right_shoe = get_object_or_404(Shoe, id=logistepsUser.right_shoe_id)

    initialHeight = {
        'height_feet': floor(logistepsUser.height / 12),
        'height_inches': logistepsUser.height % 12
    }

    userForm = UserUpdateForm(request.POST or None, instance=request.user)
    logistepsUserForm = LogistepsUserUpdateForm(request.POST or None, instance=logistepsUser, initial=initialHeight)
    leftShoeForm = ShoeUpdateForm(request.POST or None, instance=left_shoe, prefix='left')
    rightShoeForm = ShoeUpdateForm(request.POST or None, instance=right_shoe, prefix='right')

    context = {
        'userForm': userForm,
        'logistepsUserForm': logistepsUserForm,
        'leftShoeForm': leftShoeForm,
        'rightShoeForm': rightShoeForm
    }

    if request.method == 'POST':
        if userForm.is_valid() and logistepsUserForm.is_valid() and leftShoeForm.is_valid() and rightShoeForm.is_valid():
           userForm.save()
           logistepsUserForm.save()
           leftShoeForm.save()
           rightShoeForm.save()
           return redirect('/logisteps/')
    
    return render(request, 'logisteps/update_profile.html', context)

class RecentView(ProtectedView):
    template_name = 'recent.html'
    
    def formatResponse(self, data):
        steps = data.get('steps', 0)
        most_active_hour = data.get('most_active').get('hour')
        least_active_hour = data.get('least_active').get('hour')

        stats = {
            'steps': data.get('steps'),
            'least_active': to12HourTime(least_active_hour) if steps > 0 else 'N/A',
            'most_active': to12HourTime(most_active_hour) if steps > 0 else 'N/A',
            'inactive_time': data.get('inactive_time'),
            'steps_per_hour': str(round(data.get('steps_per_hour'), 2))
        }

        return stats

    def summarize(self, request, *args, **kwargs):
        today = datetime.today()

        todaySum = getDateSummary(request.user, today)
        yesterdaySum = getDateSummary(request.user, today - timedelta(days=1))

        todaySum = self.formatResponse(todaySum)
        yesterdaySum = self.formatResponse(yesterdaySum)

        return {
            'today': todaySum,
            'yesterday': yesterdaySum
        }

    def get(self, request, *args, **kwargs):
        data = self.summarize(request)

        return render(request, 'logisteps/recent.html', {'summary': data})

class StepsOverTime(ProtectedView):
    template_name = 'steps_over_time.html'

    def get(self, request, *args, **kwargs):
        return render(request, 'logisteps/steps_over_time.html')

class StepsByDay(ProtectedView):
    template_name = 'steps_by_weekday.html'

    def get(self, request, *args, **kwargs):
        return render(request, 'logisteps/steps_by_weekday.html')

class Activity(ProtectedView):
    template_name = 'activity.html'

    def get(self, request, *args, **kwargs):
        return render(request, 'logisteps/activity.html')

class PressureView(ProtectedView):
    template_name = 'pressure.html'

    def get(self, request, *args, **kwargs):
        return render(request, 'logisteps/pressure.html')

class MapView(ProtectedView):
    template_name = 'location_map.html'

    def get(self, request, *args, **kwargs):
        return render(request, 'logisteps/location_map.html')

logisteps/templates/logisteps/activity.html
{% extends "logisteps/index.html" %}

{% block page %}
<div style="height:100%">
    <div>
        <h1 style="text-align:center; padding: 30px">Weekly Activity</h1>
    </div>
    <div class="calander_week" style="display:table; margin:auto">
        <div class="month_header">
            <h2 style="display:inline-block"><span id="start_date"></span> - <span id="end_date"></span></h2>
            <div type="text" id="datepicker" style="float:right"></div>
            <div style="display:inline-block; padding: 10px"><button id="datepicker-button" style="background-color:transparent; border:none">
                <i class="fa fa-calendar fa-2x" aria-hidden="true"></i></button></div>
        </div>
        <div>
            <div id="activity_loader">
                <div class="loader"></div>
            </div>
            <table class="week">
                <tr class="week_header">
                    <th class="sunday">
                        <h2 class="date"></h2>
                        <h4 class=weekday>Sunday</h4>
                    </th>
                    <th class="monday">
                        <h2 class="date"></h2>
                        <h4 class=weekday>Monday</h4>
                    </th>
                    <th class="tuesday">
                        <h2 class="date"></h2>
                        <h4 class=weekday>Tuesday</h4>
                    </th>
                    <th class="wednesday">
                        <h2 class="date"></h2>
                        <h4 class=weekday>Wednesday</h4>
                    </th>
                    <th class="thursday">
                        <h2 class="date"></h2>
                        <h4 class=weekday>Thursday</h4>
                    </th>
                    <th class="friday">
                        <h2 class="date"></h2>
                        <h4 class=weekday>Friday</h4>
                    </th>
                    <th class="saturday">
                        <h2 class="date"></h2>
                        <h4 class=weekday>Saturday</h4>
                    </th>
                </tr>
                <tr class="week_progress">
                    <td class="sunday">
                        <div id="sunday_graph"></div>
                    </td>
                    <td class="monday">
                        <div id="monday_graph"></div>
                    </td>
                    <td class="tuesday">
                        <div id="tuesday_graph"></div>
                    </td>
                    <td class="wednesday">
                        <div id="wednesday_graph"></div>
                    </td>
                    <td class="thursday">
                        <div id="thursday_graph"></div>
                    </td>
                    <td class="friday">
                        <div id="friday_graph"></div>
                    </td>
                    <td class="saturday">
                        <div id="saturday_graph"></div>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <div class="description">
        <h3>What's this?</h3>
        <p>
            Shown here is a visual comparison of step goal completion and the ratio between active time and inactive time
            for each day of a week. The displayed week may be changed using the datepicker icon located near the page title.
        </p>
    </div>
</div>
{% load static %}
<script src="{% static 'logisteps/js/weeklyActivity.js' %}"></script>
{% endblock %}

logisteps/templates/logisteps/complete_profile.html
{% extends "base_generic.html" %}

{% block content %}

<div class="register">
    <div class="logo-banner">
        <h1 class="logo-text">LogiSteps</h1>
    </div>
    <div id="form">
        <h1>Hi {{ user.get_username }}!</h1>
        <h2>Let's Complete your Profile.</h2>

        <form method="post">
            {% csrf_token %}

            {% for hidden_field in form.hidden_fields %}
                {{ hidden_field }}
            {% endfor %}

            {% if form.non_field_errors %}
                <div class="alert alert-danger" role="alert">
                {% for error in form.non_field_errors %}
                    {{ error }}
                {% endfor %}
                </div>
            {% endif %}

            <div class="row">
                <div class="form-group col-sm-6">
                    {{ form.left_shoe.label_tag }}
                    {{ form.left_shoe }}
                </div>
                <div class="form-group col-sm-6">
                    {{ form.right_shoe.label_tag }}
                    {{ form.right_shoe }}
                </div>
            </div>
            <div class="row">
                <div class="form-group col-sm-6">
                    {{ form.height_feet.label_tag }}
                    {{ form.height_feet }}
                </div>
                <div class="form-group col-sm-6">
                    {{ form.height_inches.label_tag }}
                    {{ form.height_inches }}
                </div>
            </div>
            <div class="row">
                <div class="form-group col-sm-6">
                    {{ form.weight.label_tag }}
                    {{ form.weight }}
                </div>
                <div class="form-group col-sm-6">
                    {{ form.step_goal.label_tag }}
                    {{ form.step_goal }}
                </div>
            </div>

            
            <div><button type="submit" class="btn btn-lg btn-block">Complete</button></div>
        </form>
    </div>
</div>

{% endblock %}

logisteps/templates/logisteps/index.html
{% extends "base_generic.html" %}

{% block content %}
  <div class="row" style="height: 100%;">
    <div class="col-sm-2" style="padding-right: 0px">
      {% include "logisteps/sidebar.html" %}
    </div>
    <div class="col-sm-10">
          {% block page %}{% endblock %}
    </div>
  </div>
{% endblock %}

logisteps/templates/logisteps/location_map.html
{% extends "logisteps/index.html" %}

{% block page %}
<div>
    <h1 style="text-align:center;">
        Daily Movement
    </h1>
</div>
<div id="map"></div>
<div class="description">
    <h3>What's this?</h3>
    <p>
        This page displays your movement for the current day. GPS data collected from the mobile app is appended to step data
        originating from the smartsole technology to provide a geographical view of your fitness.
    </p>
</div>
{% load static %}
<script src="{% static 'logisteps/js/locationMap.js' %}"></script>
<script async defer>
    var script = document.createElement('script');
    script.src = `https://maps.googleapis.com/maps/api/js?key=${API_KEY}&callback=initMap`;
    document.getElementsByTagName('script')[0].parentNode.appendChild(script);
</script>
{% endblock %}

logisteps/templates/logisteps/pressure.html
{% extends "logisteps/index.html" %}

{% block page %}
<div style="height:100%">
    <div>
        <h1 style="text-align:center;">Pressure Breakdown</h1>
    </div>
    <div style="height: 70%; text-align: center">
        <div class="pressure month">
            <h3>Past Month</h3>
            <div class="shoe left">
                <img src="../../static/logisteps/images/shoe-print.svg" alt="left shoe outline">
                <p class="top-sensor"></p>
                <p class="bottom-sensor"></p>
            </div>
            <div class="shoe right">
                <img src="../../static/logisteps/images/shoe-print.svg" alt="right shoe outline">
                <p class="top-sensor"></p>
                <p class="bottom-sensor"></p>
            </div>
        </div>
        <div class="pressure week">
            <h3>Past Week</h3>
            <div class="shoe left">
                <img src="../../static/logisteps/images/shoe-print.svg" alt="left shoe outline">
                <p class="top-sensor"></p>
                <p class="bottom-sensor"></p>
            </div>
            <div class="shoe right">
                <img src="../../static/logisteps/images/shoe-print.svg" alt="right shoe outline">
                <p class="top-sensor"></p>
                <p class="bottom-sensor"></p>
            </div>
        </div>
        <div class="pressure day">
            <h3>Past Day</h3>
            <div class="shoe left">
                <img src="../../static/logisteps/images/shoe-print.svg" alt="left shoe outline">
                <p class="top-sensor"></p>
                <p class="bottom-sensor"></p>
            </div>
            <div class="shoe right">
                <img src="../../static/logisteps/images/shoe-print.svg" alt="right shoe outline">
                <p class="top-sensor"></p>
                <p class="bottom-sensor"></p>
            </div>
        </div>
    </div>
    <div class="description">
        <h3>What's this?</h3>
        <p>
            This graphic visualizes the average pressure placed on each sensor for the past day, week, and month. This
            data may be used to help you identify unhealthy amounts of pressure being applied to parts of the
            foot and make adjustments. By displaying average pressure over the past day, week, and month, you can track
            their progress. As more sensors are added to the smartsole technology, this visual will relect a visual that
            is closer and closer to a pressure gradient map.
        </p>
    </div>
</div>
{% load static %}
<script src="{% static 'logisteps/js/pressureBreakdown.js' %}"></script>
{% endblock %}

logisteps/templates/logisteps/recent.html
{% extends "logisteps/index.html" %}

{% block page %}
<div id="recent" style="height:100%">
    <div style="float: left; width: 50%; height: 100%">
        <h1>Today</h1>
        <div id="recent1" class="center-svg"></div>
        <div>
            <table class="summary">
                <tr>
                    <td>Total Steps</td>
                    <td>{{ summary.today.steps }}</td>
                </tr>
                <tr>
                    <td>Average Steps/Hr.</td>
                    <td>{{ summary.today.steps_per_hour }}</td>
                </tr>
                <tr>
                    <td>Least Active Hour</td>
                    <td> {{summary.today.least_active}} </td>
                </tr>
                <tr>
                    <td>Most Active Hour</td>
                    <td> {{summary.today.most_active}} </td>
                </tr>
                <tr>
                    <td>Inactive Time</td>
                    <td>{{ summary.today.inactive_time.hours }} Hr. {{ summary.today.inactive_time.minutes }} min.</td>
                </tr>
            </table>
        </div>
    </div>
    <div style="float: right; width: 50%; height: 100%">
        <h1>Yesterday</h1>
        <div id="recent2" class="center-svg"></div>
        <div>
            <table class="summary">
                <tr>
                    <td>Total Steps</td>
                    <td>{{ summary.yesterday.steps }}</td>
                </tr>
                <tr>
                    <td>Average Steps/Hr.</td>
                    <td>{{ summary.yesterday.steps_per_hour }}</td>
                </tr>
                <tr>
                    <td>Least Active Hour</td>
                    <td> {{summary.yesterday.least_active}} </td>
                </tr>
                <tr>
                    <td>Most Active Hour</td>
                    <td> {{summary.yesterday.most_active}} </td>
                </tr>
                <tr>
                    <td>Inactive Time</td>
                    <td>{{ summary.yesterday.inactive_time.hours }} Hr. {{ summary.today.inactive_time.minutes }} min.</td>
                </tr>
            </table>
        </div>
    </div>
</div>
{% load static %}
<script src="{% static 'logisteps/js/donut_chart.js' %}"></script>
{% endblock %}

logisteps/templates/logisteps/sidebar.html
<div class="sidenav" style="position:relative">
    <a href="{% url 'logisteps:recent'%}">Recent</a>
    <a href="{% url 'logisteps:steps_over_time' %}">Steps Trend</a>
    <a href="{% url 'logisteps:steps_by_day' %}">Weekday Breakdown</a>
    <a href="{% url 'logisteps:activity' %}">Weekly Activity</a>
    <a href="{% url 'logisteps:pressure' %}">Pressure Map</a>
    <a href="{% url 'logisteps:map' %}">Location Map</a>
    <a class="logo" href="{% url 'logisteps:recent' %}">
        <img src="../../static/logisteps/images/logo.png" alt="Logisteps Logo">
    </a>
</div>

logisteps/templates/logisteps/steps_by_weekday.html
{% extends "logisteps/index.html" %}

{% block page %}
<div style="height:100%">
    <div style="display:flex; justify-content:center">
        <h1 style="text-align:center; display: inline-block;">Weekday Breakdown</h1>
    </div>
    <div>
        <div id="weekday_breakdown"></div>
    </div>
    <div class="description">
        <h3>What's this?</h3>
        <p>
            Shown here is a graphic displaying a ratio of active time vs. inactive time, plus step count
            for the past year, broken down by weekday. This may help you identify activity tendencies for yourself,
            enabling you to determine which day of the week you may need to increase activity.
        </p>
    </div>
</div>
{% load static %}
<script src="{% static 'logisteps/js/weekdayBreakdown.js' %}"></script>
{% endblock %}

logisteps/templates/logisteps/topbar.html
{% load static %}
<nav class="navbar navbar-expand-sm navbar-dark" style="background-color: #49274A;">
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
        <a class="navbar-brand" href="{% url 'logisteps:recent' %}"><img src="{% static 'logisteps/images/logo.png' %}" alt="Logisteps Logo" height="50px" width="100px"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="">Global</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="">Connections</a>
            </li>
        </ul>
    </div>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-2x fa-user" style="color:whitesmoke; padding-left: 10px;"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right profile-dropdown" aria-labelledby="navbarDropdown">
                    {% if user.is_authenticated %}
                    <div class="profile-card">
                        <h3>{{ logistepsUser.fullname }}</h3>
                        <img src="{% static 'logisteps/images/default-profile-picpng.png' %}" alt="default profile pic" style="width: 50%">
                        <p>Username: {{ user.get_username }}</p>
                        <p><i class="far fa-envelope" style="padding-right:5px"></i>{{ user.email }}</p>
                        <P>Height: {{ logistepsUser.height_ft }}ft. {{ logistepsUser.height_in }}in.</P>
                        <p>Weight: {{ logistepsUser.weight }} lbs.</p>
                        <p>Step Goal: {{ logistepsUser.step_goal }}</p>
                    </div>
                    <div class="dropdown-divider" style="border-color:gray"></div>
                    <div>
                    <a href="{% url 'logisteps:update_profile' %}" class="btn btn-outline-secondary" role="button" style="display:block; width: 90%; margin: auto">
                        Edit Profile
                    </a>
                    </div>
                    {% endif %}
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout'%}?next={{request.path}}"><i class="fas fa-2x fa-sign-out-alt"
                        style="color:whitesmoke; padding-left: 10px;"></i></a>
            </li>
        </ul>
    </div>
</nav>